"""Initial schema

Revision ID: 80a48d366018
Revises: None
Create Date: 2026-06-25 18:40:08.589106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a48d366018'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporting_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_reporting_orders_order_id'), 'reporting_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_reporting_orders_user_id'), 'reporting_orders', ['user_id'], unique=False)
    op.create_table('reporting_payments',
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_reporting_payments_order_id'), 'reporting_payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_reporting_payments_payment_id'), 'reporting_payments', ['payment_id'], unique=False)
    op.create_table('reporting_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_reporting_profiles_user_id'), 'reporting_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reporting_profiles_user_id'), table_name='reporting_profiles')
    op.drop_table('reporting_profiles')
    op.drop_index(op.f('ix_reporting_payments_payment_id'), table_name='reporting_payments')
    op.drop_index(op.f('ix_reporting_payments_order_id'), table_name='reporting_payments')
    op.drop_table('reporting_payments')
    op.drop_index(op.f('ix_reporting_orders_user_id'), table_name='reporting_orders')
    op.drop_index(op.f('ix_reporting_orders_order_id'), table_name='reporting_orders')
    op.drop_table('reporting_orders')
    op.drop_table('outbox_messages')
    # ### end Alembic commands ###
