import re
import logging
from typing import List, AsyncIterator
from langchain_core.messages import BaseMessage
from shared.common.resilience import AsyncCircuitBreaker
from src.infrastructure.llm_setup import LLMManager

logger = logging.getLogger("LLMAdapter")

def clean_llm_response(text: str) -> str:
    """Strips chain-of-thought scratchpad blocks if generated by thinking models like Nemotron / DeepSeek"""
    if not text:
        return ""
    # 1. Strip XML <think>...</think> tags
    cleaned = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()
    
    # 2. If the model outputs "Here's a thinking process: ...", extract the actual response section
    if "thinking process:" in cleaned.lower():
        split_markers = [
            r'\n\n(?:\*\*|#|\d+\.\s*)?(?:Final Response|Customer Response|Response|Here is the response|Message to Customer)[:\s*]*\n',
            r'\n\n(?=Hello|Hi|Hey|Dear|Thank you|Here are the|Regarding your|Standard return|Our return)'
        ]
        for marker in split_markers:
            parts = re.split(marker, cleaned, flags=re.IGNORECASE)
            if len(parts) > 1 and len(parts[-1].strip()) > 20:
                return parts[-1].strip()
                
    return cleaned

class OpenRouterLLMAdapter:
    """Adapter for invoking OpenRouter Nvidia LLM with resilience, streaming support, and transient retries"""
    def __init__(self, manager: LLMManager):
        self.manager = manager
        self.breaker = AsyncCircuitBreaker(
            name="openrouter-breaker",
            failure_threshold=4,
            recovery_timeout=15.0
        )

    async def invoke(self, messages: List[BaseMessage]) -> str:
        """Invokes the OpenRouter LLM under circuit breaker protection, auto-retries transient 524/504 errors, and sanitizes scratchpad thinking"""
        async def _invoke():
            import asyncio
            max_attempts = 3
            backoff = 2.0

            for attempt in range(1, max_attempts + 1):
                try:
                    llm = self.manager.get_llm()
                    response = await llm.ainvoke(messages)
                    raw_content = str(response.content) if response and hasattr(response, "content") else ""
                    return clean_llm_response(raw_content)
                except Exception as err:
                    err_msg = str(err)
                    is_transient = any(code in err_msg for code in ["524", "504", "502", "503", "429", "timeout", "timed out", "RateLimitError"])
                    if is_transient and attempt < max_attempts:
                        logger.warning(f"OpenRouter transient error on attempt {attempt}/{max_attempts}: {err}. Retrying in {backoff:.1f}s...")
                        await asyncio.sleep(backoff)
                        backoff *= 2.0
                    else:
                        raise err

        return await self.breaker.call(_invoke)



    async def stream(self, messages: List[BaseMessage]) -> AsyncIterator[str]:
        """Streams tokens from OpenRouter LLM under circuit breaker protection"""
        llm = self.manager.get_llm()
        async for chunk in llm.astream(messages):
            if chunk.content:
                yield chunk.content
