"""Initial schema

Revision ID: c5a0b25c6bbe
Revises: None
Create Date: 2026-06-25 18:40:09.223025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a0b25c6bbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materialized_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('webhook_url', sa.String(length=255), nullable=True),
    sa.Column('is_famous', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materialized_stores_id'), 'materialized_stores', ['id'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_delivery_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('webhook_url', sa.String(length=255), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_delivery_logs_order_id'), 'webhook_delivery_logs', ['order_id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_logs_store_id'), 'webhook_delivery_logs', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_delivery_logs_store_id'), table_name='webhook_delivery_logs')
    op.drop_index(op.f('ix_webhook_delivery_logs_order_id'), table_name='webhook_delivery_logs')
    op.drop_table('webhook_delivery_logs')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_materialized_stores_id'), table_name='materialized_stores')
    op.drop_table('materialized_stores')
    # ### end Alembic commands ###
